### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by ghost** [filipw/RealtimeCart#1]
please. Where is the sql script or database ? Update-Database not working. 
No migrations configuration type was found in the assembly 'RealTimeCart'. (In Visual Studio you can use the Enable-Migrations command from Package Manager Console to add a migrations configuration).

**Comment by filipw** [comment]
There is no database, it's all in memory against a Dictionary
https://github.com/filipw/RealtimeCart/blob/master/RealTimeCart/Models/MemoryRepository.cs#L9
If you want a DB you need to create it from the models yourself, just add
EF or any other ORM you want.

**Comment by ghost** [comment]
Ok. Thank you. I was confused about the connection string on web.config :)

**Comment by filipw** [comment]
oops :)
